language: python
python:
- 3.8
script:
- python setup.py build
deploy:
  provider: pypi
  user: __token__
  password:
    secure: NjynNcYK+is3WHB8tO/RI371OH9+1/x8rEycjd6veynDxI6BbkqcP/eJ6C7d0b0B553TNJ5aY0RAzWenjGCThQ18TY2Q5IRaZgw6qqZ4lZ9mA8jsbqMgx5v4k2vDcg2uPRpKEP84detHIQI67I4jX/Sn0PHRzB1gKP/NGfS6zqbZQSHRhUcSDjsHAwCiY+FcHuuVxkbdj706cYrWS73Bc1iS3F5KCb6eyLgZyaDPA6bKl631sA6z6vv4D8LYwoHSYTOTvo4srTUevIIyoPg8b3DiFuN9HcuHOmLKvSMUqp2TsfiX+pxsKNG88z5gUl4rUg/TRW5twQUs01NMwCryGMo84e5KOlYuLR2kJlcQCI/ytSE33+rcBQPtozTPsvh2IhGtkW/13ZL+XC05HJhqpl3OCBC/niR7Ml8T9ex6LBwWLzNWOIF8cKais7qjpWUrkhQeAFg+Fwpdehvv4KBw/NsLPpPwKg1GyJg1kMC0RfRs10DiQHISZB+mEI8D9tZ6HTt9sLhvWlGJee5IKwlRTFnRfQZ/cRtfZq2deWTaPn1rpr1+SwIMpijDgTdNMRzO88Dh+vF8f6qmK7QRNFcFg0kHpXWTHGGTWnmwCxptKSwQXGmWS11dQz6fnHQ0geAmUtZJcB3Gn8bBENUC96gydHhgCaER0uwA2NA3Drirm/w=
  on:
    tags: true
    repo: cdumay/opentelemetry-instrumentation-kser
