name: CI
on:
  pull_request:
    branches:
    - 'renovate/all'
    types:
    - opened
    - synchronize
jobs:
  dump_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Bump version
      run: |
        sed -i -e "s/__version__ = .*$/__version__ = '$(grep 'opentelemetry-semantic-conventions==' requirements.txt | cut -d'=' -f3)'/g" src/opentelemetry/instrumentation/kser/version.py
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Commit changes
      run: |
        git add src/opentelemetry/instrumentation/kser/version.py
        git commit -m "build: Bump version"
    - name: Push changes
      run: |
        git push origin HEAD:${{ github.head_ref }}
