name: Publish (pypi.org)
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python install
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install build twine
      - name: Build the package
        run: python -m build --sdist
#      - name: Publish on PyPI
#        env:
#          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#        run: twine upload dist/*
